fix/error_code
dscdut/swagger-docs-api-boilerplate pull request #11
Opened 2024-06-10 14:39 UTC by PhamVanTien1910

![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/4cf50d42-ecd3-4717-a035-0433cbf4353c)
![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/2e5ef4a2-cf66-4a23-b925-aa42f55a9f46)
![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/fba47bc7-78bd-42dc-9118-5e885f339333)
![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/6bd7b1d7-1b25-48fc-89f1-ba25adcf970e)
![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/b1e2ac7b-3b01-456d-b64c-0c78128b9dd0)
![image](https://github.com/dscdut/boilerplate-api-documentation/assets/84020540/57ad1f47-1bda-4dc0-810e-afd819ba9560)

2024-06-10 14:54 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                      - Path does not exist
ủa 2 cái này cùng err code à em

2024-06-10 15:04 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                      - Path does not exist
dã update

2024-06-10 17:53 UTC, hungpham28 requested changes
Role Name nên viết hoa vì nó đại diện cho giá trị bất biến ví dụ MEMBER

2024-06-11 10:16 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        details: [Path does not exist]
nếu đã vào được endpoint để call rồi thì khi nào mới ném lỗi này?

2024-06-11 10:29 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        details: [Path does not exist]
dạ ở đó ví dụ là admin thì khi admin lấy id thì hắn sẽ có đuôi là update_user/3 thì ví dụ hắn sửa cái số 3 thành hello hay gì đó thì hắn bắn ra lỗi nớ a

2024-06-11 10:32 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        details: [Path does not exist]
anh thấy em bỏ vào tất cả api mà, như api login thì có bắn lỗi này k em?

2024-06-11 10:33 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        details: [Path does not exist]
dạ ví dụ hắn vô login thì /login xong hắn thêm là login/hello thì hắn vẫn bắn lỗi nớ mà a

2024-06-11 10:40 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        details: [Path does not exist]
nhưng đó đâu phải api mà em define nữa đâu? 
<img width="262" alt="image" src="https://github.com/dscdut/boilerplate-api-documentation/assets/62748688/5df7ac40-3f1d-411a-b8df-e5dc45cc9b5d">

2024-06-11 10:44 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        details: [Path does not exist]
nếu hắn đổi chữ login thành logins thì hắn vẫn lỗi nớ chứ a nhỉ

2024-06-11 10:51 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        details: [Path does not exist]
thì cũng đâu phải api mà em define? em define auth/login mà

2024-06-11 10:56 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        details: [Path does not exist]
ủa nếu vậy thì hắn sẽ thông báo một cái lỗi 404 chung thì mình sẽ define swagger như nào thị hợp lý anh

2024-06-16 14:31 UTC, merged