docs(GBB-108): Design API for generating payment URL
dscdut/swagger-docs-api-boilerplate pull request #15
Opened 2024-06-28 17:28 UTC by PhamVanTien1910

2024-06-29 02:13 UTC, LongTCH approved these changes

2024-07-01 16:37 UTC, hungpham28 requested changes

2024-07-01 16:37 UTC, hungpham28 commented on docs/openapi.yaml
> +                  partner_code:
trường này ẩn nha xử lí ở server side

2024-07-01 16:37 UTC, hungpham28 commented on docs/openapi.yaml
> +                  description: Information to identify the business account
chỗ này ẩn giúp mình vì phía client ko có, chỉ xử lí ở server side

2024-07-01 17:47 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                  partner_code:
dđã update

2024-07-01 17:47 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                  description: Information to identify the business account
đã update

2024-07-03 16:00 UTC, ThuongHoai081 commented on docs/openapi.yaml
> +                  description: Total amount
Số tiền thì nên để kiểu float hoặc double á em

2024-07-03 19:26 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                  description: Total amount
đã update

2024-07-05 13:36 UTC, merged