docs(GBB-44): Design API Get paginated list of users
dscdut/swagger-docs-api-boilerplate pull request #4
Opened 2024-06-01 19:09 UTC by PhamVanTien1910

2024-06-01 19:32 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        - name: limit
đổi lại thành page với page size nhé

2024-06-01 19:33 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                    example: http://localhost:3000/users?limit=2&offset=3
không cần 2 field này đâu em

2024-06-01 19:35 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                        email: "user@gmail.com"
anh thấy object này giống response register, em tạo schema nhé

2024-06-02 04:07 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                        email: "user@gmail.com"
đã update

2024-06-02 04:07 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                    example: http://localhost:3000/users?limit=2&offset=3
đã update

2024-06-02 04:07 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        - name: limit
đã update

2024-06-02 16:31 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +    data_response:
tên khác đi em, sao lại data_repsonse

2024-06-02 16:32 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        - message
ủa sao cái này là pagination_response

2024-06-02 16:36 UTC, phamhongphuc1403 requested changes
lần sau nhớ double check trước khi push em nhé

2024-06-02 18:00 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +    data_response:
đã update

2024-06-02 18:00 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        - message
đã update

2024-06-03 12:01 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +        - $ref: "#/components/parameters/page_pram"
2 cái này có cần tạo schema không em?

2024-06-03 12:03 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +        - $ref: "#/components/parameters/page_pram"
sau ở role vẫn dùng á a

2024-06-03 12:10 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
khi nào ném những lỗi này em nhỉ?

2024-06-03 12:12 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
dạ lỗi 400 khi tham số truy vấn ko hợp lệ ví dụ người dùng nhập đó là string chớ ko phải interger, còn 404 là họ nhập qua số trang á a

2024-06-03 12:14 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
lỗi 400 sao em không ném err code 104 luôn?
còn 404 nếu mình trả ra mảng rỗng thì có hợp lý hơn không?

2024-06-03 12:17 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
dạ oke a

2024-06-03 12:23 UTC, PhamVanTien1910 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
dạ nếu vậy thì mình cũng ko cần lỗi 400 luôn á a vì ở trên mình bắt họ phải luôn luôn là integer họ ko nhập đc string

2024-06-03 12:25 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +                $ref: "#/components/schemas/error_response"
thì nếu họ nhập không phải int thì ném lỗi gì em?

2024-06-03 13:34 UTC, phamhongphuc1403 commented on docs/openapi.yaml
> +    page_size_pram:
ghi luôn thêm chữ a trong pram đi em, tiết kiệm thế

2024-06-03 16:56 UTC, phamhongphuc1403 approved these changes

2024-06-03 16:58 UTC, merged